# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Location.destroy_all
Event.destroy_all

Location.create(name: "The Source Hotel", address: "3330 Brighton Blvd.", picture: "https://theknow.denverpost.com/wp-content/uploads/2018/09/the-source-hotel_AC23494x-1080x720.jpg")
Location.create(name: "Catalyst", address: "3513 Brighton Blvd.", picture: "https://assets.website-files.com/5734f8d4da0b98c8495f9a4c/5d4c64a17ec366d2cbc186c5_event-spaces-catalyst-3572A.jpg")
Location.create(name: "Big Trouble", address: "3501 Wazee St. 2nd Floor", picture: "https://s3-us-west-2.amazonaws.com/zeppelinstation/uploads/gallery_Big_Trouble_Bar_Zeppelin_Station_Denver_Colorado.jpg?mtime=20180302143102")
Location.create(name: "Helikon", address: "3675 Wynkoop St.", picture: "https://helikongallery.com/wp-content/uploads/2016/10/cropped-exterior-photo-sunsetHDR-1.jpg")
Location.create(name: "Bigsby's Folly", address: "3563 Wazee St.", picture: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/denver/Bigsby-s-Folly.14-forinternetuse_5B3D2F0F-B08C-4146-A067BC9D81DE80A0_c5399007-46fb-4e65-81b38d80650cf572.jpg")

Event.create(name: "Check In / Coffee / Breakfast", day: 1, time: "8:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "Opening Keynote, Growth: Rachel Carlson", day: 1, time: "9:00 AM", description: "", speaker_name: "Rachel Carlson", speaker_url: "", location_id: 2)
Event.create(name: "Check In Hangout", day: 1, time: "9:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "React Loves TS: Advanced TypeScript Patterns", day: 1, time: "10:00 AM", description: "Did your team recently decide to rewrite everything in TypeScript? Are you unsure, excited, or generally challenged by how to transition and grow your React application’s codebase in a typed system? Strongly typed React can seem daunting, but it empowers developers with increased speed and confidence in making code changes. It makes code extra readable, avoids bugs, speeds up onboarding, and even spell checks for you! In this talk we’ll go over some of the techniques that you can use to avoid using `any` and build your React application with rock solid types. By implementing strongly typed React patterns we’ll take advantage of TypeScript to enhance your front end skills, improve the quality of your codebase, and build clean and maintainable apps that last. If you’re working in TypeScript but struggling with how to add types to the common React patterns you’ve grown to love, this talk is for you.", speaker_name: "Crystal Preston-Watson", speaker_url: "https://developdenver.org/profiles/672", location_id: 1)
Event.create(name: "It’s Always Sunny in Mobile Accessibility", day: 1, time: "10:00 AM", description: "Do you want to be a Golden God of mobile accessibility? First you are going to need your tools. With the increased usage of mobile devices, it’s critical for development teams to understand how to build mobile applications that don’t obstruct accessibility/usability of individuals with disabilities. Currently the Web Content Accessibility Guidelines (WCAG) addresses a fraction of mobile web and native application-specific issues and largely anchors them to the standards for non-mobile software and web. Putting teams in the difficult position of having to decipher and validate their mobile accessibility approach on their own. In this talk we will discuss how WCAG can be applied to mobile web and native applications, best practices and an overview into accessibility features and tools available for both android and iOS devices. After this talk you will see how mobile accessibility is governed by reason unlike bird law. This talk is for developers and testers on teams that are supporting native/hybrid apps, but will be helpful for any developer interested in building more accessible mobile applications.", speaker_name: "Crystal Preston-Watson", speaker_url: "https://developdenver.org/profiles/672", location_id: 2)
Event.create(name: "Check In Hangout", day: 1, time: "10:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "Logging In: Creating Space for Mental Health in the Workplace", day: 1, time: "10:00 AM", description: "“Panic Attack at the Code Review” isn’t just a cool idea for a band name, it’s a real experience many people have had at work. Every business, group and congregation is neurodiverse -- and an estimated 1 in 6 people have a brain disorder. Yet, 68% of employees never discuss mental health with their employer. This is even more common in the tech industry. If you’re a developer, designer, manager or entrepreneur who’s experienced stress, burnout, anxiety or depression, this talk is for you (that’s likely 100% of you reading this!). We’ll discuss why mental health issues are common in the tech industry, and how addressing mental health at the workplace can improve your diversity and inclusion efforts. You’ll walk away with concrete tips on how to begin these discussions at your company, and some quick tips for you on how you can “log out” to take care of your own mental health.", speaker_name: "Nina Baliga", speaker_url: "https://developdenver.org/profiles/764", location_id: 4)
Event.create(name: "Writing SQL", day: 1, time: "10:00 AM", description: "SQL is a core skill for working with data of any size or complexity, but it can be daunting to get started with and it's easy to rest on the basics once you have them. In this workshop targeted at people with multiple skill levels, you'll walk away with some new SQL skills whether you've never written a query before or are just a little rusty on your PL/SQL.", speaker_name: "Elyse Coberly", speaker_url: "https://developdenver.org/", location_id: 5)
Event.create(name: "2 Fast 2 Furious", day: 1, time: "11:00 AM", description: "Web technologies are moving faster than we can keep up. After creating thousands of video tutorials, I share my secrets on how I learn web development skills quickly.", speaker_name: "Scott Tolinski", speaker_url: "https://developdenver.org/profiles/1044", location_id: 1)
Event.create(name: "Accessibility-First Development", day: 1, time: "11:00 AM", description: "In January of this year, Domino's pizza lost a court case in the Ninth Circuit Court, where the judges ruled that websites were covered under the Americans with Disabilities Act (ADA). This means that we as developers have a legal, and I would argue a moral obligation to build accessible technology for those with disabilities. We talk a lot about mobile-first development in this industry, but we need to be talking about accessibility-first development. At CirrusMD, one of our core tenets is accessibility. We work to make our product accessible to everyone, and we have garnered unique insight into how to develop with an accessibility-first mindset. The result is a better experience for everyone. We partner with the Blind Institute of Technology to provide accessibility audits of our product, and I want to share with you the "ah ha!" moments from those audits that seem so obvious after-the-fact that you can't believe you didn't think of them first. In this talk I will cover some of the quick changes you can make to your applications tomorrow to make it more accessible friendly, and I will posit how accessible-first technology is actually a better user experience for everyone, not just those with disabilities. I will be joined by Ethan Holliger, a screen-reader user, who will demonstrate a live audit of some websites.", speaker_name: "Derik Linch", speaker_url: "https://developdenver.org/profiles/84", location_id: 2)
Event.create(name: "Lightning Talks", day: 1, time: "11:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "Lunch", day: 1, time: "11:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 4)
Event.create(name: "Suck Less at Networking", day: 1, time: "11:00 AM", description: "", speaker_name: "Isaac Miller", speaker_url: "https://developdenver.org/profiles/718", location_id: 5)
Event.create(name: "Onboarding - an Investment in your company’s growth (and future)", day: 1, time: "12:00 PM", description: "The newest generations to the workforce expect to get fired from jobs as opposed to stay at them for the rest of their lives. Retaining top talent in the highly competitive and quickly expanding technology job market in Denver is a challenge and necessity. But also getting the most out of your workforce even if you only have them for a brief time. How are you laying the groundwork to get your new employees up to speed and productivity quickly when your company has a lot of domain knowledge, legacy code, esoteric processes, etc? What are you doing beyond the beginning of employment to help grow existing employees? Finding and hiring the right talent already consumes a lot of your organization’s time and resources - so don’t waste any more leaving your employees left to trial by fire. Qualifications: I’m a senior engineering manager for Quizlet in Denver and previously worked as a software engineering manager for HomeAdvisor in Denver. At HomeAdvisor I started a brand new onboarding “boot camp” for all new employees in the product/technology organization. Participants included developers (front-end, back-end, database, etc) as well as product, UX, marketing and BI people. Even as a fledgling project, employee satisfaction and retention increased dramatically, allowing the organization to continue to obtain its aggressive growth goals. Now at Quizlet, we are growing our Denver office and plan to grow 200% in the next year.", speaker_name: "Genevieve Krzeminski", speaker_url: "https://developdenver.org/profiles/1058", location_id: 1)
Event.create(name: "Lunch", day: 1, time: "12:00 PM", description: "", speaker_name: "", speaker_url: "", location_id: 2)
Event.create(name: "DevTools debugging - greatest hits!", day: 1, time: "12:00 PM", description: "Have you always wanted to get better at Chrome DevTools and move past console.logging everything? Let's take a look at this insanely powerful tool and get you solving gnarly bugs in no time! In this talk we'll focus on the Elements, Console, and Sources tabs, and dive into how to make these tools work for you. We'll work through concrete examples and show you some of the most powerful features that will quickly increase your debugging ability. Get your nerd hats on! It's gonna be a fun ride.", speaker_name: "Guillermo Moratorio", speaker_url: "https://developdenver.org/profiles/143", location_id: 4)
Event.create(name: "Lunch", day: 1, time: "1:00 PM", description: "", speaker_name: "", speaker_url: "", location_id: 1)
Event.create(name: "Most product ideas don’t work. What can we do about it?", day: 1, time: "1:00 PM", description: "Marty Cagan says: “The first inconvenient truth about product is that at least half of the ideas on your roadmap aren’t going to work”. He bases his conclusion on experience working with world-class product teams at companies of all sizes. What can we do, as founders, builders, or product leaders, to deal with this truth? How can we maximize our chance of building products our customers love? Do roadmaps even make sense in an “agile” world? Join product leaders from across the Front Range for an informal panel discussion about how to design, build, and test successful products.", speaker_name: "Chandler Koglmeier", speaker_url: "https://developdenver.org/profiles/1100", location_id: 2)
Event.create(name: "Resumes and Interviews: The Do's and Do Not's", day: 1, time: "1:00 PM", description: "Ever wonder what goes on in the mind of a hiring manager, a recruiter or another developer when they look at your resume? Or, can't understand just what your interview is trying to get at when they ask a certain question in an interview? Let us lift the veil on interviewing and resume screening and tell you about best practices from people in the industry.", speaker_name: "Becca Zukowski", speaker_url: "https://developdenver.org/profiles/1079", location_id: 4)
Event.create(name: "Cultivating Continuous Learning in Your Software Team", day: 1, time: "1:00 PM", description: "In the best engineering organizations, continuous learning is part of the software development and deployment cycle. This is achieved by team leads who cultivate a safe learning environment, and those who use teaching techniques to speed up the learning of their junior and mid-level engineers. In this interactive workshop, you’ll learn and practice 3 high-impact teaching techniques from Doug Lemov’s manual Practice Perfect. You’ll leave the workshop ready to coach your team and mentor with confidence, using the techniques Lock It In, Analyze the Game, Replace Your Purpose with an Objective. This workshop is designed for anyone who wants to help foster the development and growth of other engineers. Executives who are thinking about how to build and grow their software teams, Senior Engineers who want to coach and teach engineers with confidence and junior engineers who want to get better at coaching themselves and their peers.", speaker_name: "Kim Schlesinger", speaker_url: "https://developdenver.org/", location_id: 5)
Event.create(name: "Prototypes! Why tell you when I can show you?", day: 1, time: "2:00 PM", description: "Generally, we think of prototyping as part of the overall design process, it has its time and place, but why stop to only discuss the product? What if we looked at prototyping beyond the product and into the possibilities aligning a team? We'll go over a variety of prototypes, when and why they can be used and a variety of tools that can help facilitate the development process of a prototype.", speaker_name: "Yadira Valadez Galan", speaker_url: "https://developdenver.org/profiles/171", location_id: 1)
Event.create(name: "It's Dangerous to go Alone, Take This: Navigating React Native", day: 1, time: "2:00 PM", description: "You're just getting into React Native with a brilliant, world-changing idea — but wait! How do you switch screens? What if you want fancy screen transitions? Let this talk be your pathfinder into all things navigation with React Navigation. Open your eyes to a world of routing, drawer navigation, tabbed navigation, passing parameters via navigation state — and so much more!", speaker_name: "Gabi Procell", speaker_url: "https://developdenver.org/profiles/758", location_id: 2)
Event.create(name: "Improving on Express", day: 1, time: "2:00 PM", description: "alternate title: oh no, am I really writing a js framework… Express has served the Node.js community pretty well, but it's starting to show its age. Frameworks from other languages have explored new ground, and we can learn from their work. We can leverage TypeScript to improve our ability to reason about code, and catch errors early. In this talk, I will propose a new framework that improves upon express, specifically in these ways: Built on express' foundation. No reason to throw away the many existing libraries and codebases already using express. Promises instead of callbacks. Return values instead of mutations. In addition to the usual benefits, this change makes controllers and middleware easier to test and more composable. We'll see that promises also help with type safety. Resource-based workflows should be easy. It's common to need the whole bevy of CRUD endpoints, and to treat them similarly. This case should be handled more easily. Whether these ideas turn into a new library or just a set of patterns, I'm looking forward to sharing what I learn!", speaker_name: "Brian Schiller", speaker_url: "https://developdenver.org/profiles/287", location_id: 4)
Event.create(name: "Suck Less at Interviewing", day: 1, time: "2:30pm", description: "Interviewing is hard, but there’s good news: most interviewers use a predictable set of questions, and we know the best way to answer them. Join us to learn the secret! In this workshop, we will practice and refine your answers for the following interview questions: Tell me about yourself Tell me about a time you handled a challenge at work Come prepared to quickly improve your answers and walk out of the room ready for your next interview.", speaker_name: "Kyle Coberly", speaker_url: "https://developdenver.org/", location_id: 5)
Event.create(name: "Strengthen Your Coding Immune System: How to Debug Smarter", day: 1, time: "3:00 PM", description: "Our immune systems can be amazing. They are adaptive, resilient, and ready to fight off all kinds of bugs for us. You might be worried that I’m about to send you back to middle school biology, but I promise I’m not. Wouldn’t it be great to have a debugging tool that could do all of that and so much more? It could learn about bugs and adapt to recognize the signs, so that it’s always ready to implement a fix. Once it does, it knows how to tackle that bug more effectively in the future. The good news is that you already have such a tool in your toolbox! (It’s you) In this talk we’ll go over why you should be treating your debugging skills like your immune system and training them every chance you get. We’ll cover how how to use errors to your advantage, how to build up a bug catalogue, and what to do when your immune system needs some help. This talk is for anyone who writes code.", speaker_name: "Marlena Baker", speaker_url: "https://developdenver.org/profiles/193", location_id: 1)
Event.create(name: "Dynamic CSS", day: 1, time: "3:00 PM", description: "Don’t be fooled by the declarative syntax, CSS is a powerful language for building dynamic design systems. CSS has come a long way since the browser wars of the late 90s. What used to be a struggle, is now often a breeze (see box-shadow or border-radius). But the last 2 years have pushed CSS into entirely new territory: with DOM-aware variables and calculations and grids that can drive complex designs, without any invasive Javascript. Basics for understanding Custom Properties & Calc() & Grids Functions, Mixins, and Components with plain CSS Practical examples and use-cases for data-infused CSS", speaker_name: "Miriam Suzanne", speaker_url: "https://developdenver.org/profiles/269", location_id: 2)
Event.create(name: "Beyond the keg: How to build and maintain a thriving company culture", day: 1, time: "3:00 PM", description: "It’s simple: Happy people stick around and do great work. When our company experienced 4 acquisitions over a 5 year period, a strong company culture was the one thing that bolstered employee morale and maintained their sense of purpose. Join us for a candid discussion on how to define, build, and maintain a strong sense of culture at your company.", speaker_name: "Angela Daniels", speaker_url: "https://developdenver.org/profiles/1051", location_id: 4)
Event.create(name: "The WAFL: An MVP alternative that will bring your team joy", day: 1, time: "4:00 PM", description: "Our UI at CircleCI needed a major redesign. Yes, we still wanted a nimble approach and fast feedback. But we’d seen that early over-reliance on an MVP mentality didn’t scale well– The code architecture was irrevocably fickle and the UI looked like a tiny home with 6 bedroom additions and 12 different wallpapers. So we invented our own MVP alternative: The WAFL. WAFL stands for “Well Architected, Functionally Limited.” The idea behind a WAFL is to create (or recreate) the basic functionality of a project in a codebase that can scale. You architect your new front-end codebase with the robust framing, pervasive testing, accessibility, and responsiveness to service the world. However, you only add back in one functionality at a time. Are there other, more precise, acronyms we could have come up with? Possibly, but making WAFLs pun jokes all day makes our team smile a waffle lot (get it?). This will be a talk about our lessons learned with this approach: The right recipe for success, serving it up half-baked, savoring the feedback, and lots and lots of groan-worthy puns. If you’re not convinced, read this CFP again, it’s batter the second time around.", speaker_name: "Kate Catlin", speaker_url: "https://developdenver.org/profiles/1086", location_id: 1)
Event.create(name: "UI Design for VR", day: 1, time: "4:00 PM", description: "If you were working a VR food truck, how would you let the simulation know you were ready to leave? Try to walk out the door? Look for a “exit” button? In Job Simulator, you take a bite out of a burrito labeled “quit” - twice to confirm your choice. It’s just one of many ways designers are experimenting with UI design in VR. In this talk, Senior UX Instructor Nick Anderson will explore the Wild West of VR UI design, from simple floating interfaces to true-to-life, fully integrated experiences. We’ll look at indications of where we can expect these trends to go next, and how it will impact the jobs of UX Designers. Finally, we’ll explore how gamification design plays a role in simulated experiences.", speaker_name: "Nick Anderson", speaker_url: "https://developdenver.org/profiles/969", location_id: 2)
Event.create(name: "DVLP Jeopardy", day: 1, time: "4:00 PM", description: "", speaker_name: "CJ Reynolds", speaker_url: "https://developdenver.org/", location_id: 3)
Event.create(name: "Learning to Love Vim", day: 1, time: "4:00 PM", description: "As developers, we use text editors day in and day out. For years I knew just enough about Vim to be dangerous and I absolutely should have learned it sooner. I finally made the decision to jump into the deep end of Vim and use it as my primary editor for as much as possible. After a huge struggle and learning curve, I managed to gain competence in the tool, and even learned to love it. In this talk we will explore my journey, highlighting the elegant feature set, patterns of usage, extensibility, efficiency, and even joy of using Vim as your everyday editing companion. We will learn about buffers, registers, macros, and more. Through this journey I found that I am far more efficient in my editor than ever before and by the end of this talk you will understand why it is such an important tool to learn to use as well.", speaker_name: "Heath Naylor", speaker_url: "https://developdenver.org/profiles/87", location_id: 4)
Event.create(name: "Opening Night Happy Hour", day: 1, time: "5:00 PM", description: "", speaker_name: "", speaker_url: "", location_id: 1)