# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Location.destroy_all
Event.destroy_all

Location.create(name: "The Source Hotel", address: "3330 Brighton Blvd.", picture: "https://theknow.denverpost.com/wp-content/uploads/2018/09/the-source-hotel_AC23494x-1080x720.jpg")
Location.create(name: "Catalyst", address: "3513 Brighton Blvd.", picture: "https://assets.website-files.com/5734f8d4da0b98c8495f9a4c/5d4c64a17ec366d2cbc186c5_event-spaces-catalyst-3572A.jpg")
Location.create(name: "Big Trouble", address: "3501 Wazee St. 2nd Floor", picture: "https://s3-us-west-2.amazonaws.com/zeppelinstation/uploads/gallery_Big_Trouble_Bar_Zeppelin_Station_Denver_Colorado.jpg?mtime=20180302143102")
Location.create(name: "Helikon", address: "3675 Wynkoop St.", picture: "https://helikongallery.com/wp-content/uploads/2016/10/cropped-exterior-photo-sunsetHDR-1.jpg")
Location.create(name: "Bigsby's Folly", address: "3563 Wazee St.", picture: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/denver/Bigsby-s-Folly.14-forinternetuse_5B3D2F0F-B08C-4146-A067BC9D81DE80A0_c5399007-46fb-4e65-81b38d80650cf572.jpg")

Event.create(name: "Check In / Coffee / Breakfast", day: 1, time: "8:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "Opening Keynote, Growth: Rachel Carlson", day: 1, time: "9:00 AM", description: "", speaker_name: "Rachel Carlson", speaker_url: "", location_id: 2)
Event.create(name: "Check In Hangout", day: 1, time: "9:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "React Loves TS: Advanced TypeScript Patterns", day: 1, time: "10:00 AM", description: "Did your team recently decide to rewrite everything in TypeScript? Are you unsure, excited, or generally challenged by how to transition and grow your React application’s codebase in a typed system? Strongly typed React can seem daunting, but it empowers developers with increased speed and confidence in making code changes. It makes code extra readable, avoids bugs, speeds up onboarding, and even spell checks for you! In this talk we’ll go over some of the techniques that you can use to avoid using `any` and build your React application with rock solid types. By implementing strongly typed React patterns we’ll take advantage of TypeScript to enhance your front end skills, improve the quality of your codebase, and build clean and maintainable apps that last. If you’re working in TypeScript but struggling with how to add types to the common React patterns you’ve grown to love, this talk is for you.", speaker_name: "Crystal Preston-Watson", speaker_url: "https://developdenver.org/profiles/672", location_id: 2)
Event.create(name: "Check In Hangout", day: 1, time: "10:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "Logging In: Creating Space for Mental Health in the Workplace", day: 1, time: "10:00 AM", description: "“Panic Attack at the Code Review” isn’t just a cool idea for a band name, it’s a real experience many people have had at work. Every business, group and congregation is neurodiverse -- and an estimated 1 in 6 people have a brain disorder. Yet, 68% of employees never discuss mental health with their employer. This is even more common in the tech industry. If you’re a developer, designer, manager or entrepreneur who’s experienced stress, burnout, anxiety or depression, this talk is for you (that’s likely 100% of you reading this!). We’ll discuss why mental health issues are common in the tech industry, and how addressing mental health at the workplace can improve your diversity and inclusion efforts. You’ll walk away with concrete tips on how to begin these discussions at your company, and some quick tips for you on how you can “log out” to take care of your own mental health.", speaker_name: "Nina Baliga", speaker_url: "https://developdenver.org/profiles/764", location_id: 4)
Event.create(name: "Writing SQL", day: 1, time: "10:00 AM", description: "SQL is a core skill for working with data of any size or complexity, but it can be daunting to get started with and it's easy to rest on the basics once you have them. In this workshop targeted at people with multiple skill levels, you'll walk away with some new SQL skills whether you've never written a query before or are just a little rusty on your PL/SQL.", speaker_name: "Elyse Coberly", speaker_url: "https://developdenver.org/", location_id: 5)
Event.create(name: "2 Fast 2 Furious", day: 1, time: "11:00 AM", description: "Web technologies are moving faster than we can keep up. After creating thousands of video tutorials, I share my secrets on how I learn web development skills quickly.", speaker_name: "Scott Tolinski", speaker_url: "https://developdenver.org/profiles/1044", location_id: 1)
Event.create(name: "Accessibility-First Development", day: 1, time: "11:00 AM", description: "In January of this year, Domino's pizza lost a court case in the Ninth Circuit Court, where the judges ruled that websites were covered under the Americans with Disabilities Act (ADA). This means that we as developers have a legal, and I would argue a moral obligation to build accessible technology for those with disabilities. We talk a lot about mobile-first development in this industry, but we need to be talking about accessibility-first development. At CirrusMD, one of our core tenets is accessibility. We work to make our product accessible to everyone, and we have garnered unique insight into how to develop with an accessibility-first mindset. The result is a better experience for everyone. We partner with the Blind Institute of Technology to provide accessibility audits of our product, and I want to share with you the "ah ha!" moments from those audits that seem so obvious after-the-fact that you can't believe you didn't think of them first. In this talk I will cover some of the quick changes you can make to your applications tomorrow to make it more accessible friendly, and I will posit how accessible-first technology is actually a better user experience for everyone, not just those with disabilities. I will be joined by Ethan Holliger, a screen-reader user, who will demonstrate a live audit of some websites.", speaker_name: "Derik Linch", speaker_url: "https://developdenver.org/profiles/84", location_id: 2)
Event.create(name: "Lightning Talks", day: 1, time: "11:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 3)
Event.create(name: "Lunch", day: 1, time: "11:00 AM", description: "", speaker_name: "", speaker_url: "", location_id: 4)
Event.create(name: "Suck Less at Networking", day: 1, time: "11:00 AM", description: "", speaker_name: "Isaac Miller", speaker_url: "https://developdenver.org/profiles/718", location_id: 5)
Event.create(name: "Onboarding - an Investment in your company’s growth (and future)", day: 1, time: "12:00 PM", description: "The newest generations to the workforce expect to get fired from jobs as opposed to stay at them for the rest of their lives. Retaining top talent in the highly competitive and quickly expanding technology job market in Denver is a challenge and necessity. But also getting the most out of your workforce even if you only have them for a brief time. How are you laying the groundwork to get your new employees up to speed and productivity quickly when your company has a lot of domain knowledge, legacy code, esoteric processes, etc? What are you doing beyond the beginning of employment to help grow existing employees? Finding and hiring the right talent already consumes a lot of your organization’s time and resources - so don’t waste any more leaving your employees left to trial by fire. Qualifications: I’m a senior engineering manager for Quizlet in Denver and previously worked as a software engineering manager for HomeAdvisor in Denver. At HomeAdvisor I started a brand new onboarding “boot camp” for all new employees in the product/technology organization. Participants included developers (front-end, back-end, database, etc) as well as product, UX, marketing and BI people. Even as a fledgling project, employee satisfaction and retention increased dramatically, allowing the organization to continue to obtain its aggressive growth goals. Now at Quizlet, we are growing our Denver office and plan to grow 200% in the next year.", speaker_name: "Genevieve Krzeminski", speaker_url: "https://developdenver.org/profiles/1058", location_id: 1)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 2)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 4)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 1)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 2)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 4)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 5)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 1)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: 2)
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: )
Event.create(name: "", day: , time: "", description: "", speaker_name: "", speaker_url: "", location_id: )